package ru.job4j.rest.service;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import ru.job4j.rest.cxf.*;

/**
 * This class was generated by Apache CXF 4.0.4
 * 2024-03-30T17:19:51.957+03:00
 * Generated source version: 4.0.4
 *
 */
@WebService(targetNamespace = "http://localhost:9912", name = "StudentsStorageService")
@XmlSeeAlso({ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface StudentsStorageService {

    @WebMethod(action = "urn:GetOneStudent")
    @WebResult(name = "StudentOneResponse", targetNamespace = "http://", partName = "parameters")
    public StudentOneResponse getOneStudent(

        @WebParam(partName = "parameters", name = "StudentOneRequest", targetNamespace = "http://")
                StudentOneRequest parameters
    );

    @WebMethod(action = "urn:GetAllStudents")
    @WebResult(name = "StudentsResponse", targetNamespace = "http://", partName = "parameters")
    public StudentsResponse getAllStudents(

        @WebParam(partName = "parameters", name = "StudentsRequest", targetNamespace = "http://")
                StudentsRequest parameters
    );
}
